### ISSUE TITLE
Doesn't work on Unity 5.6.0f3

### ISSUE THREAD

**Issue by madcoffee** [poisins/WebGLCustomTemplate_U3D#1]
Hi, I tested this on Unity 5.5 and it worked but then I decided to update my Unity to 5.6 and now it doesn't seem to work. It didn't process any of the Template Tags

**Comment by sandolkakos** [comment]
The Template has changed in Unity 5.6.0.
You can find the Default Template here:

`C:\Program Files\Unity\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\WebGLTemplates\Default`

**Comment by poisins** [comment]
At last upgraded to Unity 2017.1, and created template based on that version. Could work on 5.6 as well
